export const GET_CURRENT_DATE = 'GET_CURRENT_DATE';
export const GET_DISPLAYED_MONTH_DAYS = 'GET_DISPLAYED_MONTH_DAYS';
export const GET_PREVIOUS_MONTH = 'GET_PREVIOUS_MONTH';
export const GET_NEXT_MONTH = 'GET_NEXT_MONTH';
export const GET_PREVIOUS_YEAR = 'GET_PREVIOUS_YEAR';
export const GET_NEXT_YEAR = 'GET_NEXT_YEAR';

export const UPDATE_YEAR_MONTH_DATE = 'UPDATE_YEAR_MONTH_DATE';

export const SELECTED_FULL_DATE = 'SELECTED_FULL_DATE';

export const ADD_MEETING = 'ADD_MEETING';
export const DELETE_MEETING = 'DELETE_MEETING';
export const MEETING_ADDED = 'MEETING_ADDED';

export const GET_MEETINGS = 'GET_MEETINGS';
export const TOGGLE_MEETING_MODAL = 'TOGGLE_MEETING_MODAL';

export const SET_SORTING_CATEGORY = 'SET_SORTING_CATEGORY';
export const START_SORTING_MEETINGS = 'START_SORTING_MEETINGS';
export const SET_SORTING_TO_ALL = 'SET_SORTING_TO_ALL';
